### ISSUE TITLE
amend.fromConfig Not Working

### ISSUE THREAD

**Issue by ibrido90** [TheLudd/amend#3]
Hello copy and pasted your example (which would be awesome to download) but at row
`var di = amend.fromConfig(config)`
got an error like:
```
throw new TypeError('No configuration was provided for loadConfig');
    ^

TypeError: No configuration was provided for loadConfig
    at Object.module.exports [as fromConfig] (C:\MYPATH\amend_di\node_modules\amend\dist\load-config.js:89:11)
    at Object.<anonymous> (C:\MYPATH\amend_
di\main.js:23:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

I am sure that config.json gets loaded fine beacuse i logged it's content before

**Comment by ibrido90** [comment]
Ok so after some digging into your API i discovered two errors in the example:

1. you name a file *playGame.js* but in config.json is referenced as _**play-game.js**_
2. the *amend.fromConfig(config)* expects an _**OBJECT**_ with, at least, a property named *config*:

> ```
> var opts = {
>   config: /*retrieve the config file*/
> }
> var di = amend.fromConfig(opts)
> ```
